title: Vishal Shah
logo: <img src="images/Rounded%20dp.pngâ€> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  &#128073; Hi, I'm Vishal&#128075; A certified data analyst using R, SQL &#38; Excel&#128515;
  <br>
  &#128188; I have experience in solving business problems using data analytics &#38; machine learning for 6+ projects &#128526;
  <br>
  &#127891; I have a Bachelors degree(BSc) in economics and I am currently pursuing Masters(MSc) in supply chain management&#127793;
  <br><br>
  &#9996; Give me data and I shall offer you actionable insights&#128161;
  <br><br>
  <a href="linkedin.com/in/vishalshah98">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-Y4G2D492RC # your Google Analytics tracking ID here
